<?php
return[
	'role' => [
        1 => 'Vendor',
        2 => 'Super Admin',
        3 => 'Delivery',
        4 => 'Customer',
    ],
    'reservation_system' => [
        1 => 'Grub Hub',
        2 => 'Uber Eats',
        3 => 'In House',
        4 => 'Other',
    ],
    'us_states' => [
        "CA"=>"California",
        "AL"=>"Alabama",
        "AK"=>"Alaska",
        "AZ"=>"Arizona",
        "AR"=>"Arkansas",
        "CO"=>"Colorado",
        "CT"=>"Connecticut",
        "DE"=>"Delaware",
        "DC"=>"District Of Columbia",
        "FL"=>"Florida",
        "GA"=>"Georgia",
        "HI"=>"Hawaii",
        "ID"=>"Idaho",
        "IL"=>"Illinois",
        "IN"=>"Indiana",
        "IA"=>"Iowa",
        "KS"=>"Kansas",
        "KY"=>"Kentucky",
        "LA"=>"Louisiana",
        "ME"=>"Maine",
        "MD"=>"Maryland",
        "MA"=>"Massachusetts",
        "MI"=>"Michigan",
        "MN"=>"Minnesota",
        "MS"=>"Mississippi",
        "MO"=>"Missouri",
        "MT"=>"Montana",
        "NE"=>"Nebraska",
        "NV"=>"Nevada",
        "NH"=>"New Hampshire",
        "NJ"=>"New Jersey",
        "NM"=>"New Mexico",
        "NY"=>"New York",
        "NC"=>"North Carolina",
        "ND"=>"North Dakota",
        "OH"=>"Ohio",
        "OK"=>"Oklahoma",
        "OR"=>"Oregon",
        "PA"=>"Pennsylvania",
        "RI"=>"Rhode Island",
        "SC"=>"South Carolina",
        "SD"=>"South Dakota",
        "TN"=>"Tennessee",
        "TX"=>"Texas",
        "UT"=>"Utah",
        "VT"=>"Vermont",
        "VA"=>"Virginia",
        "WA"=>"Washington",
        "WV"=>"West Virginia",
        "WI"=>"Wisconsin",
        "WY"=>"Wyoming",
    ],
    'birthday_club' => [
        1 => "Free meal Maximum discount is $10.00",
        2 => "Dine in only",
        3 => "Dine in only with purchase of One drinks of any kind",
        4 => "Valid on any day of the month of your birthday except",
        5 => "Not valid with any other offer",
        6 => "Not valid on holiday",
        7 => "Not valid on special events",
        8 => "Only one offer per table", 
    ],
    'aaadining_club' => [
        1 => "Maximum discount is $10.00",
        2 => "Dine in only",
        3 => "Dine in only with purchase of Two drinks of any kind", 
        4 => "Not valid with any other offer", 
        5 => "Not valid on holiday",
        6 => "Not valid on special events",
        7 => "Only one offer per table", 
    ],
    'days' => [
        1 => "Monday",
        2 => "Tuesday",
        3 => "Wednesday",
        4 => "Thursday",
        5 => "Friday",
        6 => "Saturday",
        7 => "Sunday",
    ],
    'time' => [
        1 => "9 to 6",
        2 => "9 to 5",
        3 => "9 to 7",
        4 => "9 to 8",
        5 => "9 to 9",
    ],
];